language: go

go:
  - 1.x

services:
  - docker

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - docker build -t image-service .

deploy:
  - provider: script
    script: bash .docker_push
    on:
      branch: main

after_script:
  - docker-compose down
