language: go

go:
  - 1.x

services:
  - docker

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - docker build -t alisavch/api:latest -f Dockerfile .
  - docker build -t alisavch/consumer:latest -f Dockerfile-consumer .

jobs:
  include:
    - stage: build
      script: bash .docker_push
    - stage: deploy
      script: aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE} --force-new-deployment
      on:
        branch: bugfix-main
