language: go

go:
  - 1.x

services:
  - docker

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

deploy:
  provider: script
  script: bash .aws_ecs_push
  on:
    branch: main

after_script:
  - docker-compose down
