language: go

go:
  - 1.x

services:
  - docker

env:
  - ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  - SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  - REGION: $AWS_REGION

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

jobs:
  include:
    - stage: build
      script: bash ./scripts/.docker_push
    - stage: deploy
      script: bash ./scripts/.aws_ecs_update
