language: go

go:
  - 1.x

services:
  - docker

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - docker build -t alisavch/image-service:latest -f Dockerfile .

deploy:
  - provider: script
    script: bash .docker_push
    on:
      branch: main
  - provider: elasticbeanstalk
    region: $AWS_REGION
    app: $AWS_EB_APP_NAME
    env: $AWS_EB_APP_ENV
    bucket_name: $AWS_EB_BUCKET_NAME
    bucket_path: $AWS_EB_APP_NAME
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY

after_script:
  - docker-compose down
