version: '3.8'

services:
  image-service:
    build: ./
    container_name: image-service
    command: ./main
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - fullstack

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - fullstack

volumes:
  api:
  database_postgres:
networks:
  fullstack:
    driver: bridge