version: '3.3'

services:
  backend:
    image: alisavch/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    restart: always
    ports:
      - "8080:8080"

  consumer:
    image: alisavch/consumer:latest
    build:
      context: .
      dockerfile: Dockerfile-consumer
    container_name: consumer
    env_file: .env
    restart: always
    depends_on:
      - backend
