version: '3.8'

services:
  image-service:
    build: ./
    container_name: image-service
    command: ./image-service
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq