FROM golang:alpine as builder
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
RUN apk --no-cache add build-base git gcc make

RUN go get github.com/sirupsen/logrus
RUN go get github.com/streadway/amqp
RUN go get github.com/joho/godotenv

WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o consumer ./cmd/consumer/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder ["/app/consumer", "/"]
COPY .env /

ENTRYPOINT ["/consumer"]