basePath: /
consumes:
- application/json
definitions:
  Image:
    description: An image is what is processed in the application.
    properties:
      id:
        $ref: '#/definitions/UUID'
      resulted_location:
        description: the resulted location for this image
        type: string
        x-go-name: ResultedLocation
      resulted_name:
        description: the resulted name for this image
        type: string
        x-go-name: ResultedName
      uploaded_location:
        description: the uploaded location for this image
        type: string
        x-go-name: UploadedLocation
      uploaded_name:
        description: the uploaded name for this image
        type: string
        x-go-name: UploadedName
    required:
    - uploaded_name
    - uploaded_location
    title: Image contains details of a single request.
    type: object
    x-go-package: github.com/alisavch/image-service/internal/models
  UUID:
    description: |-
      A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC
      4122.
    items:
      format: uint8
      type: integer
    type: array
    x-go-package: github.com/google/uuid
  User:
    description: A user is the security principal for this application.
    properties:
      id:
        $ref: '#/definitions/UUID'
      password:
        description: the password for this user
        type: string
        x-go-name: Password
      username:
        description: the username for this user
        type: string
        x-go-name: Username
    required:
    - username
    - password
    title: User contains information about user.
    type: object
    x-go-package: github.com/alisavch/image-service/internal/models
host: localhost:8080
info:
  description: Documentation of our awesome API
  title: Golang SwaggerUI image-service
  version: 1.0.0
paths:
  /api/compress:
    post:
      description: Receives an image from an input form and compresses it, also allows
        you to enter width in the query string.
      operationId: compress
      parameters:
      - in: query
        name: width
        type: integer
      - in: body
        name: uploadFile
        required: true
        schema:
          $ref: '#/definitions/Image'
      responses:
        "202":
          description: request accepted
        "401":
          description: login required
        "500":
          description: internal server error
      summary: Compresses the image.
      tags:
      - compress
  /api/convert:
    post:
      description: Receives an image from an input form and converts it PNG to JPG
        and vice versa.
      operationId: convert
      parameters:
      - in: body
        name: uploadFile
        required: true
        schema:
          $ref: '#/definitions/Image'
      responses:
        "202":
          description: request accepted
        "401":
          description: login required
        "500":
          description: internal server error
      summary: Converts the image.
      tags:
      - convert
  /api/download/{requestID}:
    get:
      description: Downloads the processed image and original if required.
      operationId: findImage
      parameters:
      - description: requestID for image search
        in: path
        name: requestID
        required: true
        type: integer
      - description: if the parameter is true, the original image will be downloaded.
        in: query
        name: original
        type: boolean
      responses:
        "200":
          description: successful operation
        "401":
          description: login required
        "403":
          description: forbidden
        "404":
          description: image not found
        "409":
          description: image is being processed
        "500":
          description: internal server error
      summary: Finds and downloads an image.
      tags:
      - findImage
  /api/health:
    post:
      description: Checks the health of the api.
      operationId: health
      responses:
        "200":
          description: healthy
        "405":
          description: unhealthy
      summary: Checks the health of the api.
      tags:
      - health
  /api/history:
    get:
      description: Lists all queries created by user.
      operationId: history
      responses:
        "200":
          description: successful operation
        "401":
          description: login required
        "404":
          description: history not found
      summary: Finds users history.
      tags:
      - history
  /api/sign-in:
    post:
      description: Only authorized user has access.
      operationId: sign-in
      parameters:
      - description: the user to create
        in: body
        name: user
        schema:
          $ref: '#/definitions/User'
      responses:
        "200":
          description: successful operation
        "401":
          description: login required
      summary: Authorizes the user.
      tags:
      - sign-in
  /api/sign-up:
    post:
      description: Could be any user.
      operationId: sign-up
      parameters:
      - description: the user to create
        in: body
        name: user
        schema:
          $ref: '#/definitions/User'
      responses:
        "201":
          description: user registered successfully
        "400":
          description: bad request
        "409":
          description: user already exists
        "500":
          description: internal server error
      summary: Registers a user.
      tags:
      - sign-up
  /api/status/{requestID}:
    get:
      description: Finds the status of the request.
      operationId: findRequestStatus
      parameters:
      - description: requestID to filter by id
        in: path
        name: requestID
        required: true
        type: integer
      responses:
        "200":
          description: successful operation
        "401":
          description: login required
        "403":
          description: forbidden
        "404":
          description: status not fund
      summary: Finds the status of the request.
      tags:
      - findRequestStatus
produces:
- application/json
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
