// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	service "github.com/alisavch/image-service/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// EncodeOption is an autogenerated mock type for the EncodeOption type
type EncodeOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: config
func (_m *EncodeOption) Execute(config *service.EncodeConfig) {
	_m.Called(config)
}
