// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FormattingOutput is an autogenerated mock type for the FormattingOutput type
type FormattingOutput struct {
	mock.Mock
}

// Fatalf provides a mock function with given fields: format, args
func (_m *FormattingOutput) Fatalf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
