// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	amqp "github.com/streadway/amqp"

	mock "github.com/stretchr/testify/mock"

	models "github.com/alisavch/image-service/internal/models"
)

// AMQP is an autogenerated mock type for the AMQP type
type AMQP struct {
	mock.Mock
}

// DeclareQueue provides a mock function with given fields: name
func (_m *AMQP) DeclareQueue(name string) (amqp.Queue, error) {
	ret := _m.Called(name)

	var r0 amqp.Queue
	if rf, ok := ret.Get(0).(func(string) amqp.Queue); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(amqp.Queue)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Publish provides a mock function with given fields: exchange, key, message
func (_m *AMQP) Publish(exchange string, key string, message models.QueuedMessage) error {
	ret := _m.Called(exchange, key, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, models.QueuedMessage) error); ok {
		r0 = rf(exchange, key, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
