// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// S3Bucket is an autogenerated mock type for the S3Bucket type
type S3Bucket struct {
	mock.Mock
}

// DownloadFromS3Bucket provides a mock function with given fields: filename
func (_m *S3Bucket) DownloadFromS3Bucket(filename string) (*os.File, error) {
	ret := _m.Called(filename)

	var r0 *os.File
	if rf, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = rf(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadToS3Bucket provides a mock function with given fields: file, filename
func (_m *S3Bucket) UploadToS3Bucket(file io.Reader, filename string) (string, error) {
	ret := _m.Called(file, filename)

	var r0 string
	if rf, ok := ret.Get(0).(func(io.Reader, string) string); ok {
		r0 = rf(file, filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Reader, string) error); ok {
		r1 = rf(file, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
